"""Generate a standalone HTTPS entry point for an immutable frontend release."""

import argparse
import ipaddress
import re
from pathlib import Path, PurePosixPath
from urllib.parse import urlsplit


def config_path(value: str) -> str:
    path = PurePosixPath(value)
    if not path.is_absolute() or ".." in path.parts or not re.fullmatch(r"[A-Za-z0-9_/. +\-]+", value):
        raise ValueError("Paths must be absolute Linux paths without configuration expressions")
    return '"' + value + '"'


def nginx_config(
    *,
    origin: str,
    frontend: str,
    certificate: str,
    private_key: str,
    run_directory: str,
    bind: str = "0.0.0.0",
    api_port: int = 8080,
    office_origin: str = "",
) -> str:
    address = urlsplit(origin)
    if (
        address.scheme != "https"
        or not address.hostname
        or address.username is not None
        or address.password is not None
        or address.path
        or address.query
        or address.fragment
        or origin != "https://" + address.netloc
        or not re.fullmatch(r"[a-z0-9]+(?:[a-z0-9.\-]*[a-z0-9])?(?::[0-9]+)?", address.netloc)
    ):
        raise ValueError("Origin must be a lowercase HTTPS DNS name or IPv4 address, with optional port")
    port = address.port if address.port is not None else 443
    if not 1 <= port <= 65535 or not 1 <= api_port <= 65535:
        raise ValueError("Invalid listen port")
    if address.port is not None and (port == 443 or address.netloc != f"{address.hostname}:{port}"):
        raise ValueError("Use the canonical HTTPS origin: omit port 443 and port leading zeros")
    ipaddress.IPv4Address(bind)
    root, cert, key, runtime = map(config_path, (frontend, certificate, private_key, run_directory))
    authority = address.netloc
    if office_origin and not re.fullmatch(
        r"https://[a-z0-9]+(?:[a-z0-9.\-]*[a-z0-9])?(?::[1-9][0-9]{0,4})?", office_origin
    ):
        raise ValueError("Editor must be an explicit HTTPS origin")
    office_script = " " + office_origin if office_origin else ""
    office_frame = "; frame-src " + office_origin if office_origin else ""
    csp = (
        f"default-src 'none'; script-src 'self'{office_script}; style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; "
        "base-uri 'none'; form-action 'self'; frame-ancestors 'none'" + office_frame
    )
    # Host is checked before proxying; forwarded values are generated by this entry point.
    return rf"""# Generated by alpendata_api.ingress. Keep the API on loopback.
daemon off;
worker_processes 1;
pid {config_path(str(PurePosixPath(run_directory) / "nginx.pid"))};
error_log /dev/null;
events {{ worker_connections 1024; }}
http {{
    access_log off;
    server_tokens off;
    default_type application/octet-stream;
    types {{
        text/html html;
        text/css css;
        application/javascript js;
        image/webp webp;
        image/png png;
        image/svg+xml svg;
        image/x-icon ico;
        font/woff2 woff2;
    }}
    client_body_temp_path {runtime};
    proxy_temp_path {runtime};
    fastcgi_temp_path {runtime};
    uwsgi_temp_path {runtime};
    scgi_temp_path {runtime};
    server {{
        listen {bind}:{port} ssl default_server;
        server_name {address.hostname};
        if ($http_host != "{authority}") {{ return 421; }}
        ssl_certificate {cert};
        ssl_certificate_key {key};
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_tickets off;
        root {root};
        disable_symlinks on;
        client_max_body_size 8m;
        client_body_buffer_size 8m;
        client_body_timeout 30s;
        client_header_timeout 15s;
        send_timeout 120s;
        keepalive_timeout 30s;
        add_header Cache-Control "no-store" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer" always;
        add_header X-Frame-Options "DENY" always;
        add_header Strict-Transport-Security "max-age=86400" always;
        add_header Content-Security-Policy "{csp}" always;

        location /api/ {{
            proxy_pass http://127.0.0.1:{api_port};
            proxy_http_version 1.1;
            proxy_set_header Host "{authority}";
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host "";
            proxy_set_header Forwarded "";
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_cache off;
            proxy_next_upstream off;
            proxy_connect_timeout 5s;
            proxy_read_timeout 120s;
            proxy_send_timeout 120s;
            proxy_hide_header Cache-Control;
            proxy_hide_header X-Content-Type-Options;
            proxy_hide_header Referrer-Policy;
        }}
        location = / {{ try_files /index.html =404; }}
        location = /join {{ try_files /index.html =404; }}
        location ~ ^/assets/[A-Za-z0-9_-]+\.(js|css)$ {{ try_files $uri =404; }}
        location ~ ^/brand/[A-Za-z0-9_-]+\.(webp|png|svg|ico|woff2)$ {{ try_files $uri =404; }}
        location / {{ return 404; }}
    }}
}}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("origin", "frontend", "certificate", "private-key", "run-directory", "output"):
        parser.add_argument("--" + name, required=True)
    parser.add_argument("--bind", default="0.0.0.0")
    parser.add_argument("--api-port", type=int, default=8080)
    parser.add_argument("--office-origin", default="")
    args = vars(parser.parse_args())
    output = Path(args.pop("output"))
    configuration = nginx_config(**args)
    # An existing configuration may serve users. Generate a candidate instead of replacing it.
    with output.open("x", encoding="utf-8", newline="\n") as stream:
        stream.write(configuration)


if __name__ == "__main__":
    main()
