import { useEffect, useState } from 'react';
import { api } from './api';
import { Notice } from './feedback';
import { PublishConversation } from './ProjectResources';
import type { Project } from './ProjectPanel';
import { ChatResponse } from './ChatResponse';
import type { Language } from './locale';

interface Entry { id: string; kind: string; title: string; content: string; version: number }
export function PersonalKnowledge({ organizationId, language, choose }: { organizationId: string; language: Language; choose?: (prompt: string) => void }) {
  const fr = language === 'fr', root = `/api/organizations/${organizationId}/knowledge`;
  const [entries, setEntries] = useState<Entry[]>([]), [editing, setEditing] = useState<Entry | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(false);
  const [projects, setProjects] = useState<Project[]>([]), [publication, setPublication] = useState<{ entry: Entry; projectId: string } | null>(null);
  const chatBase = `/api/organizations/${organizationId}/chat`;
  useEffect(() => { let active = true; api<{ projects: Project[] }>(chatBase + '/projects').then(value => { if (active) setProjects(value.projects.filter(project => project.role !== 'reader')); }).catch(() => {}); return () => { active = false; }; }, [chatBase]);
  useEffect(() => { let active = true; api<{ entries: Entry[] }>(root).then(value => { if (active) setEntries(value.entries); }).catch(() => { if (active) setError(true); }); return () => { active = false; }; }, [root]);
  return <section className="personal-knowledge"><h3>{fr ? 'Mes préférences et méthodes' : 'My preferences and methods'}</h3><p>{fr ? 'Réutilisées uniquement dans votre espace personnel. Les informations propres à un client restent dans son projet.' : 'Reusable only in your personal workspace. Client-specific information stays in its project.'}</p><Notice>{error && (fr ? 'La modification n’a pas pu être confirmée. Votre texte reste disponible ; vérifiez la version actuelle avant de réessayer.' : 'The change could not be confirmed. Your text remains available; check the current version before retrying.')}</Notice>
    {entries.map(entry => <article key={entry.id}><small>{entry.kind === 'method' ? fr ? 'Méthode' : 'Method' : fr ? 'Préférence' : 'Preference'} · v{entry.version}</small><h4>{entry.title}</h4><ChatResponse text={entry.content} language={language} /><div className="message-actions"><button disabled={busy} onClick={() => setEditing({ ...entry })}>{fr ? 'Modifier' : 'Edit'}</button><button disabled={busy} onClick={async () => { setBusy(true); try { await api(root + '/' + entry.id, undefined, 'DELETE'); setEntries(items => items.filter(item => item.id !== entry.id)); } catch { setError(true); } finally { setBusy(false); } }}>{fr ? 'Supprimer' : 'Delete'}</button>{entry.kind === 'method' && choose && <button onClick={() => choose(`${fr ? 'Lis et applique ma méthode' : 'Read and apply my method'} « ${entry.title} » (ID ${entry.id}). ${fr ? 'Demande-moi les informations manquantes avant de commencer.' : 'Ask me for missing information before starting.'}`)}>{fr ? 'Utiliser dans la discussion' : 'Use in conversation'}</button>}</div>{entry.kind === 'method' && projects.length > 0 && <label>{fr ? 'Publier une copie dans un projet' : 'Publish a copy to a project'}<select value="" onChange={event => { if (event.target.value) setPublication({ entry, projectId: event.target.value }); }}><option value="">{fr ? 'Choisir le projet…' : 'Choose a project…'}</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>}</article>)}
    <button className="secondary" disabled={busy} onClick={() => setEditing({ id: crypto.randomUUID(), kind: 'preference', title: '', content: '', version: 0 })}>{fr ? 'Ajouter une préférence ou méthode' : 'Add a preference or method'}</button>
    {editing && <form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(false); try {
      const saved = await api<Entry>(root + '/' + editing.id, { kind: editing.kind, title: editing.title, content: editing.content, version: editing.version }, 'PUT');
      setEntries(items => [...items.filter(item => item.id !== saved.id), saved]); setEditing(null);
    } catch { setError(true); } finally { setBusy(false); } }}><label>{fr ? 'Type' : 'Type'}<select value={editing.kind} onChange={event => setEditing({ ...editing, kind: event.target.value })}><option value="preference">{fr ? 'Préférence personnelle' : 'Personal preference'}</option><option value="method">{fr ? 'Méthode réutilisable' : 'Reusable method'}</option></select></label><label>{fr ? 'Titre' : 'Title'}<input required maxLength={160} value={editing.title} onChange={event => setEditing({ ...editing, title: event.target.value })} /></label><label>{fr ? 'Contenu' : 'Content'}<textarea required maxLength={20000} rows={8} value={editing.content} onChange={event => setEditing({ ...editing, content: event.target.value })} /></label><button className="primary" disabled={busy}>{fr ? 'Enregistrer' : 'Save'}</button><button type="button" className="text-button" disabled={busy} onClick={() => setEditing(null)}>{fr ? 'Annuler' : 'Cancel'}</button></form>}
    {publication && <PublishConversation base={chatBase} projectId={publication.projectId} title={publication.entry.title} transcript={publication.entry.content} language={language} kind="method" close={() => setPublication(null)} />}
    <p className="subtle">{fr ? 'Une suppression retire l’entrée de cette bibliothèque. Les passages déjà cités dans vos discussions restent dans leur historique.' : 'Deleting an entry removes it from this library. Passages already quoted in conversations remain in their history.'}</p>
  </section>;
}
