"""enterprise identities and private resources

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("seat_capacity", sa.Integer(), nullable=False),
        sa.CheckConstraint("seat_capacity > 0", name="ck_organization_seats"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alpendata_users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("verified_email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject"),
    )
    op.create_table(
        "alpendata_auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["alpendata_users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_alpendata_auth_sessions_user_id"), "alpendata_auth_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "alpendata_memberships",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("licensed", sa.Boolean(), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'member')", name="ck_membership_role"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["alpendata_organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["alpendata_users.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "user_id"),
    )
    op.create_table(
        "alpendata_invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("recipient_email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.Integer(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("inviter_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "inviter_id"],
            ["alpendata_memberships.organization_id", "alpendata_memberships.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["alpendata_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_alpendata_invitations_organization_id"),
        "alpendata_invitations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "alpendata_onboardings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("step", sa.String(length=24), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("language IN ('fr', 'en')", name="ck_onboarding_language"),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_id"],
            ["alpendata_memberships.organization_id", "alpendata_memberships.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "owner_id"),
    )
    op.create_index(
        op.f("ix_alpendata_onboardings_organization_id"),
        "alpendata_onboardings",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_onboardings_owner_id"), "alpendata_onboardings", ["owner_id"], unique=False
    )
    op.create_table(
        "alpendata_personal_resources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("kind IN ('memory', 'conversation')", name="ck_personal_resource_kind"),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_id"],
            ["alpendata_memberships.organization_id", "alpendata_memberships.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alpendata_personal_resources_organization_id"),
        "alpendata_personal_resources",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_personal_resources_owner_id"),
        "alpendata_personal_resources",
        ["owner_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alpendata_personal_resources_owner_id"), table_name="alpendata_personal_resources")
    op.drop_index(
        op.f("ix_alpendata_personal_resources_organization_id"), table_name="alpendata_personal_resources"
    )
    op.drop_table("alpendata_personal_resources")
    op.drop_index(op.f("ix_alpendata_onboardings_owner_id"), table_name="alpendata_onboardings")
    op.drop_index(op.f("ix_alpendata_onboardings_organization_id"), table_name="alpendata_onboardings")
    op.drop_table("alpendata_onboardings")
    op.drop_index(op.f("ix_alpendata_invitations_organization_id"), table_name="alpendata_invitations")
    op.drop_table("alpendata_invitations")
    op.drop_table("alpendata_memberships")
    op.drop_index(op.f("ix_alpendata_auth_sessions_user_id"), table_name="alpendata_auth_sessions")
    op.drop_table("alpendata_auth_sessions")
    op.drop_table("alpendata_users")
    op.drop_table("alpendata_organizations")
    # ### end Alembic commands ###
