"""personal conversations and model usage

Revision ID: 0005
Revises: 0004
"""

import sqlalchemy as sa
from alembic import op

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("language IN ('fr', 'en')", name="ck_conversation_language"),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_id"],
            ["alpendata_memberships.organization_id", "alpendata_memberships.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id", "owner_id"),
    )
    op.create_index(
        op.f("ix_alpendata_conversations_organization_id"),
        "alpendata_conversations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_conversations_owner_id"), "alpendata_conversations", ["owner_id"], unique=False
    )
    op.create_table(
        "alpendata_chat_turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("lease_id", sa.String(length=36), nullable=True),
        sa.Column("lease_expires_at", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'cancelled', 'interrupted')",
            name="ck_chat_turn_status",
        ),
        sa.CheckConstraint("sequence > 0", name="ck_chat_turn_sequence"),
        sa.ForeignKeyConstraint(
            ["conversation_id", "organization_id", "owner_id"],
            [
                "alpendata_conversations.id",
                "alpendata_conversations.organization_id",
                "alpendata_conversations.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "sequence"),
        sa.UniqueConstraint("id", "organization_id", "owner_id"),
        sa.UniqueConstraint("organization_id", "owner_id", "request_id"),
    )
    op.create_index(
        op.f("ix_alpendata_chat_turns_conversation_id"),
        "alpendata_chat_turns",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_chat_turns_lease_expires_at"),
        "alpendata_chat_turns",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_chat_turns_organization_id"),
        "alpendata_chat_turns",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_chat_turns_owner_id"), "alpendata_chat_turns", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_alpendata_chat_turns_status"), "alpendata_chat_turns", ["status"], unique=False)
    op.create_table(
        "alpendata_model_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("prompt_tokens", sa.BigInteger(), nullable=True),
        sa.Column("completion_tokens", sa.BigInteger(), nullable=True),
        sa.Column("total_tokens", sa.BigInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("status IN ('started', 'completed', 'failed')", name="ck_model_call_status"),
        sa.CheckConstraint(
            "prompt_tokens >= 0 AND completion_tokens >= 0 AND total_tokens >= 0", name="ck_model_call_tokens"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id", "organization_id", "owner_id"],
            [
                "alpendata_chat_turns.id",
                "alpendata_chat_turns.organization_id",
                "alpendata_chat_turns.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alpendata_model_calls_organization_id"),
        "alpendata_model_calls",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_model_calls_owner_id"), "alpendata_model_calls", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_alpendata_model_calls_turn_id"), "alpendata_model_calls", ["turn_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alpendata_model_calls_turn_id"), table_name="alpendata_model_calls")
    op.drop_index(op.f("ix_alpendata_model_calls_owner_id"), table_name="alpendata_model_calls")
    op.drop_index(op.f("ix_alpendata_model_calls_organization_id"), table_name="alpendata_model_calls")
    op.drop_table("alpendata_model_calls")
    op.drop_index(op.f("ix_alpendata_chat_turns_status"), table_name="alpendata_chat_turns")
    op.drop_index(op.f("ix_alpendata_chat_turns_owner_id"), table_name="alpendata_chat_turns")
    op.drop_index(op.f("ix_alpendata_chat_turns_organization_id"), table_name="alpendata_chat_turns")
    op.drop_index(op.f("ix_alpendata_chat_turns_lease_expires_at"), table_name="alpendata_chat_turns")
    op.drop_index(op.f("ix_alpendata_chat_turns_conversation_id"), table_name="alpendata_chat_turns")
    op.drop_table("alpendata_chat_turns")
    op.drop_index(op.f("ix_alpendata_conversations_owner_id"), table_name="alpendata_conversations")
    op.drop_index(op.f("ix_alpendata_conversations_organization_id"), table_name="alpendata_conversations")
    op.drop_table("alpendata_conversations")
    # ### end Alembic commands ###
