"""personal proposals trials and source receipts

Revision ID: 0006
Revises: 0005
"""

import sqlalchemy as sa
from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_routine_proposals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("template", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("benefit", sa.Text(), nullable=False),
        sa.Column("focus", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id", "organization_id", "owner_id"],
            [
                "alpendata_conversations.id",
                "alpendata_conversations.organization_id",
                "alpendata_conversations.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "template"),
        sa.UniqueConstraint("id", "organization_id", "owner_id"),
    )
    op.create_index(
        op.f("ix_alpendata_routine_proposals_conversation_id"),
        "alpendata_routine_proposals",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_routine_proposals_organization_id"),
        "alpendata_routine_proposals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_routine_proposals_owner_id"),
        "alpendata_routine_proposals",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "alpendata_routine_trials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id", "organization_id", "owner_id"],
            [
                "alpendata_routine_proposals.id",
                "alpendata_routine_proposals.organization_id",
                "alpendata_routine_proposals.owner_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id", "organization_id", "owner_id"],
            [
                "alpendata_chat_turns.id",
                "alpendata_chat_turns.organization_id",
                "alpendata_chat_turns.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turn_id"),
    )
    op.create_index(
        op.f("ix_alpendata_routine_trials_organization_id"),
        "alpendata_routine_trials",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_routine_trials_owner_id"), "alpendata_routine_trials", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_alpendata_routine_trials_proposal_id"),
        "alpendata_routine_trials",
        ["proposal_id"],
        unique=False,
    )
    op.create_table(
        "alpendata_tool_reads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("capability", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("status IN ('started', 'completed', 'failed')", name="ck_tool_read_status"),
        sa.ForeignKeyConstraint(
            ["turn_id", "organization_id", "owner_id"],
            [
                "alpendata_chat_turns.id",
                "alpendata_chat_turns.organization_id",
                "alpendata_chat_turns.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alpendata_tool_reads_organization_id"),
        "alpendata_tool_reads",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_tool_reads_owner_id"), "alpendata_tool_reads", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_alpendata_tool_reads_turn_id"), "alpendata_tool_reads", ["turn_id"], unique=False
    )
    op.add_column(
        "alpendata_conversations",
        sa.Column("purpose", sa.String(length=24), server_default="chat", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alpendata_conversations", "purpose")
    op.drop_index(op.f("ix_alpendata_tool_reads_turn_id"), table_name="alpendata_tool_reads")
    op.drop_index(op.f("ix_alpendata_tool_reads_owner_id"), table_name="alpendata_tool_reads")
    op.drop_index(op.f("ix_alpendata_tool_reads_organization_id"), table_name="alpendata_tool_reads")
    op.drop_table("alpendata_tool_reads")
    op.drop_index(op.f("ix_alpendata_routine_trials_proposal_id"), table_name="alpendata_routine_trials")
    op.drop_index(op.f("ix_alpendata_routine_trials_owner_id"), table_name="alpendata_routine_trials")
    op.drop_index(op.f("ix_alpendata_routine_trials_organization_id"), table_name="alpendata_routine_trials")
    op.drop_table("alpendata_routine_trials")
    op.drop_index(op.f("ix_alpendata_routine_proposals_owner_id"), table_name="alpendata_routine_proposals")
    op.drop_index(
        op.f("ix_alpendata_routine_proposals_organization_id"), table_name="alpendata_routine_proposals"
    )
    op.drop_index(
        op.f("ix_alpendata_routine_proposals_conversation_id"), table_name="alpendata_routine_proposals"
    )
    op.drop_table("alpendata_routine_proposals")
    # ### end Alembic commands ###
