"""personal recurring schedules and occurrences

Revision ID: 0007
Revises: 0006
"""

import sqlalchemy as sa
from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_routine_schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("reviewed_turn_id", sa.String(length=36), nullable=False),
        sa.Column("activation_request_id", sa.String(length=36), nullable=False),
        sa.Column("frequency", sa.String(length=16), nullable=False),
        sa.Column("local_time", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("next_run_at", sa.Integer(), nullable=True),
        sa.Column("reason_code", sa.String(length=80), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "frequency IN ('daily', 'weekdays', 'weekly')", name="ck_routine_schedule_frequency"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'blocked', 'archived')", name="ck_routine_schedule_status"
        ),
        sa.CheckConstraint(
            "weekday >= 0 AND weekday <= 6 AND version > 0 AND failure_count >= 0",
            name="ck_routine_schedule_values",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id", "organization_id", "owner_id"],
            [
                "alpendata_routine_proposals.id",
                "alpendata_routine_proposals.organization_id",
                "alpendata_routine_proposals.owner_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_turn_id", "organization_id", "owner_id"],
            [
                "alpendata_chat_turns.id",
                "alpendata_chat_turns.organization_id",
                "alpendata_chat_turns.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id", "owner_id"),
        sa.UniqueConstraint("organization_id", "owner_id", "activation_request_id"),
        sa.UniqueConstraint("proposal_id"),
    )
    op.create_index(
        op.f("ix_alpendata_routine_schedules_next_run_at"),
        "alpendata_routine_schedules",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_routine_schedules_organization_id"),
        "alpendata_routine_schedules",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_routine_schedules_owner_id"),
        "alpendata_routine_schedules",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "alpendata_routine_occurrences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schedule_id", sa.String(length=36), nullable=False),
        sa.Column("schedule_version", sa.Integer(), nullable=False),
        sa.Column("scheduled_for", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "(outcome = 'queued' AND turn_id IS NOT NULL) OR (outcome = 'missed' AND turn_id IS NULL)",
            name="ck_routine_occurrence_turn",
        ),
        sa.CheckConstraint("outcome IN ('queued', 'missed')", name="ck_routine_occurrence_outcome"),
        sa.ForeignKeyConstraint(
            ["schedule_id", "organization_id", "owner_id"],
            [
                "alpendata_routine_schedules.id",
                "alpendata_routine_schedules.organization_id",
                "alpendata_routine_schedules.owner_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id", "organization_id", "owner_id"],
            [
                "alpendata_chat_turns.id",
                "alpendata_chat_turns.organization_id",
                "alpendata_chat_turns.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "scheduled_for"),
        sa.UniqueConstraint("turn_id"),
    )
    op.create_index(
        op.f("ix_alpendata_routine_occurrences_organization_id"),
        "alpendata_routine_occurrences",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_routine_occurrences_owner_id"),
        "alpendata_routine_occurrences",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_routine_occurrences_schedule_id"),
        "alpendata_routine_occurrences",
        ["schedule_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_alpendata_routine_occurrences_schedule_id"), table_name="alpendata_routine_occurrences"
    )
    op.drop_index(
        op.f("ix_alpendata_routine_occurrences_owner_id"), table_name="alpendata_routine_occurrences"
    )
    op.drop_index(
        op.f("ix_alpendata_routine_occurrences_organization_id"), table_name="alpendata_routine_occurrences"
    )
    op.drop_table("alpendata_routine_occurrences")
    op.drop_index(op.f("ix_alpendata_routine_schedules_owner_id"), table_name="alpendata_routine_schedules")
    op.drop_index(
        op.f("ix_alpendata_routine_schedules_organization_id"), table_name="alpendata_routine_schedules"
    )
    op.drop_index(
        op.f("ix_alpendata_routine_schedules_next_run_at"), table_name="alpendata_routine_schedules"
    )
    op.drop_table("alpendata_routine_schedules")
    # ### end Alembic commands ###
