"""private document downloads

Revision ID: 0008
Revises: 0007
"""

import sqlalchemy as sa
from alembic import op

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=180), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("size > 0 AND size <= 5242880", name="ck_artifact_size"),
        sa.ForeignKeyConstraint(
            ["turn_id", "organization_id", "owner_id"],
            [
                "alpendata_chat_turns.id",
                "alpendata_chat_turns.organization_id",
                "alpendata_chat_turns.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turn_id", "filename", "sha256"),
    )
    op.create_index(
        op.f("ix_alpendata_artifacts_organization_id"),
        "alpendata_artifacts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_artifacts_owner_id"), "alpendata_artifacts", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_alpendata_artifacts_turn_id"), "alpendata_artifacts", ["turn_id"], unique=False)
    op.add_column(
        "alpendata_conversations",
        sa.Column("documents_enabled", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alpendata_conversations", "documents_enabled")
    op.drop_index(op.f("ix_alpendata_artifacts_turn_id"), table_name="alpendata_artifacts")
    op.drop_index(op.f("ix_alpendata_artifacts_owner_id"), table_name="alpendata_artifacts")
    op.drop_index(op.f("ix_alpendata_artifacts_organization_id"), table_name="alpendata_artifacts")
    op.drop_table("alpendata_artifacts")
    # ### end Alembic commands ###
