"""reviewed SharePoint saves

Revision ID: 0010
Revises: 0009
"""

import sqlalchemy as sa
from alembic import op

revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("alpendata_artifacts") as batch:
        batch.create_unique_constraint("uq_artifact_owner", ["id", "organization_id", "owner_id"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_sharepoint_saves",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("drive_id", sa.String(length=512), nullable=False),
        sa.Column("folder_id", sa.String(length=512), nullable=False),
        sa.Column("folder_name", sa.String(length=1024), nullable=False),
        sa.Column("folder_url", sa.String(length=4096), nullable=True),
        sa.Column("filename", sa.String(length=180), nullable=False),
        sa.Column("existing_id", sa.String(length=512), nullable=True),
        sa.Column("existing_etag", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "status IN ('review', 'running', 'completed', 'failed', 'unknown')",
            name="ck_sharepoint_save_status",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id", "organization_id", "owner_id"],
            ["alpendata_artifacts.id", "alpendata_artifacts.organization_id", "alpendata_artifacts.owner_id"],
            name="fk_sharepoint_save_artifact_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alpendata_sharepoint_saves_artifact_id"),
        "alpendata_sharepoint_saves",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_sharepoint_saves_organization_id"),
        "alpendata_sharepoint_saves",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_sharepoint_saves_owner_id"),
        "alpendata_sharepoint_saves",
        ["owner_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alpendata_sharepoint_saves_owner_id"), table_name="alpendata_sharepoint_saves")
    op.drop_index(
        op.f("ix_alpendata_sharepoint_saves_organization_id"), table_name="alpendata_sharepoint_saves"
    )
    op.drop_index(op.f("ix_alpendata_sharepoint_saves_artifact_id"), table_name="alpendata_sharepoint_saves")
    op.drop_table("alpendata_sharepoint_saves")
    with op.batch_alter_table("alpendata_artifacts") as batch:
        batch.drop_constraint("uq_artifact_owner", type_="unique")
    # ### end Alembic commands ###
