"""organization access rules

Revision ID: 0011
Revises: 0010
"""

import sqlalchemy as sa
from alembic import op

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_organization_policies",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("allowed_capabilities", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.CheckConstraint("version > 0", name="ck_organization_policy_version"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["alpendata_organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["alpendata_users.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alpendata_organization_policies")
    # ### end Alembic commands ###
