"""personal email reviews

Revision ID: 0012
Revises: 0011
"""

import sqlalchemy as sa
from alembic import op

revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_email_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("initial_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("version > 0", name="ck_email_draft_version"),
        sa.ForeignKeyConstraint(
            ["turn_id", "organization_id", "owner_id"],
            [
                "alpendata_chat_turns.id",
                "alpendata_chat_turns.organization_id",
                "alpendata_chat_turns.owner_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id", "owner_id", name="uq_email_draft_owner"),
        sa.UniqueConstraint("turn_id", "initial_hash"),
    )
    op.create_index(
        op.f("ix_alpendata_email_drafts_organization_id"),
        "alpendata_email_drafts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_email_drafts_owner_id"), "alpendata_email_drafts", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_alpendata_email_drafts_turn_id"), "alpendata_email_drafts", ["turn_id"], unique=False
    )
    op.create_table(
        "alpendata_email_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "status IN ('sending', 'accepted', 'failed', 'unknown')", name="ck_email_attempt_status"
        ),
        sa.ForeignKeyConstraint(
            ["draft_id", "organization_id", "owner_id"],
            [
                "alpendata_email_drafts.id",
                "alpendata_email_drafts.organization_id",
                "alpendata_email_drafts.owner_id",
            ],
            name="fk_email_attempt_draft_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "version"),
    )
    op.create_index(
        op.f("ix_alpendata_email_attempts_draft_id"), "alpendata_email_attempts", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_alpendata_email_attempts_organization_id"),
        "alpendata_email_attempts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_email_attempts_owner_id"), "alpendata_email_attempts", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alpendata_email_attempts_owner_id"), table_name="alpendata_email_attempts")
    op.drop_index(op.f("ix_alpendata_email_attempts_organization_id"), table_name="alpendata_email_attempts")
    op.drop_index(op.f("ix_alpendata_email_attempts_draft_id"), table_name="alpendata_email_attempts")
    op.drop_table("alpendata_email_attempts")
    op.drop_index(op.f("ix_alpendata_email_drafts_turn_id"), table_name="alpendata_email_drafts")
    op.drop_index(op.f("ix_alpendata_email_drafts_owner_id"), table_name="alpendata_email_drafts")
    op.drop_index(op.f("ix_alpendata_email_drafts_organization_id"), table_name="alpendata_email_drafts")
    op.drop_table("alpendata_email_drafts")
    # ### end Alembic commands ###
