"""email sent copy verification

Revision ID: 0013
Revises: 0012
"""

import sqlalchemy as sa
from alembic import op

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alpendata_email_attempts", sa.Column("correlation_id", sa.String(length=36), nullable=True)
    )
    op.add_column("alpendata_email_attempts", sa.Column("verification", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alpendata_email_attempts", "verification")
    op.drop_column("alpendata_email_attempts", "correlation_id")
    # ### end Alembic commands ###
