"""personal email autonomy

Revision ID: 0014
Revises: 0013
"""

import sqlalchemy as sa
from alembic import op

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_personal_action_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email_mode", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("email_mode IN ('confirm', 'automatic')", name="ck_personal_email_mode"),
        sa.CheckConstraint("version > 0", name="ck_personal_action_version"),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_id"],
            ["alpendata_memberships.organization_id", "alpendata_memberships.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "owner_id"),
    )
    op.create_index(
        op.f("ix_alpendata_personal_action_policies_organization_id"),
        "alpendata_personal_action_policies",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alpendata_personal_action_policies_owner_id"),
        "alpendata_personal_action_policies",
        ["owner_id"],
        unique=False,
    )
    op.add_column(
        "alpendata_conversations",
        sa.Column("email_send_enabled", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "alpendata_email_attempts",
        sa.Column("initiator", sa.String(length=16), server_default="browser", nullable=False),
    )
    op.add_column("alpendata_email_attempts", sa.Column("autonomy_version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alpendata_email_attempts", "autonomy_version")
    op.drop_column("alpendata_email_attempts", "initiator")
    op.drop_column("alpendata_conversations", "email_send_enabled")
    op.drop_index(
        op.f("ix_alpendata_personal_action_policies_owner_id"),
        table_name="alpendata_personal_action_policies",
    )
    op.drop_index(
        op.f("ix_alpendata_personal_action_policies_organization_id"),
        table_name="alpendata_personal_action_policies",
    )
    op.drop_table("alpendata_personal_action_policies")
    # ### end Alembic commands ###
