"""explicit company resources and grants

Revision ID: 0017
Revises: 0016
"""

import sqlalchemy as sa
from alembic import op

revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpendata_company_resources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("filename", sa.String(length=180), nullable=True),
        sa.Column("media_type", sa.String(length=120), nullable=True),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.CheckConstraint("audience IN ('team', 'selected')", name="ck_company_resource_audience"),
        sa.CheckConstraint("kind IN ('note', 'document')", name="ck_company_resource_kind"),
        sa.CheckConstraint("version > 0 AND size >= 0", name="ck_company_resource_values"),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by"],
            ["alpendata_memberships.organization_id", "alpendata_memberships.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id"),
        sa.UniqueConstraint("organization_id", "created_by", "request_id"),
    )
    op.create_index(
        op.f("ix_alpendata_company_resources_organization_id"),
        "alpendata_company_resources",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "alpendata_company_resource_grants",
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["alpendata_memberships.organization_id", "alpendata_memberships.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id", "organization_id"],
            ["alpendata_company_resources.id", "alpendata_company_resources.organization_id"],
        ),
        sa.PrimaryKeyConstraint("resource_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alpendata_company_resource_grants")
    op.drop_index(
        op.f("ix_alpendata_company_resources_organization_id"), table_name="alpendata_company_resources"
    )
    op.drop_table("alpendata_company_resources")
    # ### end Alembic commands ###
